# Generated by Django 3.1.2 on 2020-10-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('education', models.TextField()),
                ('skills', models.TextField()),
                ('social', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=300)),
            ],
        ),
    ]
